replicaCount: 3

image:
  repository: jabok123458/ai-service
  pullPolicy: Always
  tag: eabbad277d4abaed7c2addd4d063fb0bdb0e3926

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    memory: "150Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

secret:
  DB_HOST: Y29ybmVsaXVzLmRiLmVsZXBoYW50c3FsLmNvbQ==
  DB_PORT: NTQzMg==
  DB_USER: Z2VncXNsdm4=
  DB_PASSWORD: TGdTdlNWV0xpM212MEpsVEdJZTZtczBoM0hXZ0xIQ08=
  DB_NAME: Z2VncXNsdm4=
  OPENTRIPMAP_API_KEY: OThmMTcwN2E4N21zaDMzMWU0YzdkMzI1YzZmZnAxNGZjYTRqc24zNjUxYWViOTQ4Y2Q=
  AILAB_API_KEY: QURSbzVQeFhWN1FHaUlkNVh1YnNNWk5LM0FUN2taNDIxbmNJdzZNc3ZteFBOejlhRmVDdGZGcFJoYmo4U3lXZg==