replicaCount: 2

image:
  repository: jabok123458/gallery-frontend
  pullPolicy: Always
  tag: fd4639656c108734aaec7e6e5c1bba01e3ca38d3

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000 # Frontend port

secret:
  VITE_AUTH_API_URL: MzQuMTQwLjE4Ny44MQ==
  VITE_PHOTOS_API_URL: MzQuMjIuMjAzLjIyNA==

resources:
  limits:
    memory: "150Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80