replicaCount: 2

image:
  repository: jabok123458/gallery-frontend
  pullPolicy: Always
  tag: 070975c1aaef9b219b20062f60c776eec24552ea

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000 # Frontend port

resources:
  limits:
    memory: "150Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80