replicaCount: 3

image:
  repository: jabok123458/rso_prepih
  pullPolicy: Always
  tag: 25fd3e76a1d4583e9e82c47873facd8b33416913

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080


resources:
  limits:
    memory: "150Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

secret:
  DB_HOST: Y29ybmVsaXVzLmRiLmVsZXBoYW50c3FsLmNvbQ==
  DB_PORT: NTQzMg==
  DB_USER: Z2VncXNsdm4=
  DB_PASSWORD: TGdTdlNWV0xpM212MEpsVEdJZTZtczBoM0hXZ0xIQ08=
  DB_NAME: Z2VncXNsdm4=
  