apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-service.fullname" . }}-pdb
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "auth-service.fullname" . }}