apiVersion: v1
kind: Service
metadata:
  name: {{ include "img-info-service.fullname" . }}
  labels:
    {{- include "img-info-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
  selector:
    {{- include "img-info-service.selectorLabels" . | nindent 4 }}