apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: Y29ybmVsaXVzLmRiLmVsZXBoYW50c3FsLmNvbQ==
  DB_PORT: NTQzMg==
  DB_USER: Z2VncXNsdm4=
  DB_PASSWORD: TGdTdlNWV0xpM212MEpsVEdJZTZtczBoM0hXZ0xIQ08=
  DB_NAME: Z2VncXNsdm4=
