apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gallery-service
  template:
    metadata:
      labels:
        app: gallery-service
    spec:
      containers:
      - name: gallery-service
        image: jabok123458/rso_prepih:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"  
            memory: "250Mi"
          limits:
            cpu: "3"
            memory: "2Gi"
        envFrom:
        - secretRef:
            name: db-secret
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5