apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gallery-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gallery-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80