replicaCount: 2

image:
  repository: tinec/auth
  tag: 2274764f1374df1571391dea2a629fb35ae52680
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    memory: "150Mi"

probes:
  liveness:
    path: /live
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5

pdb:
  minAvailable: 1

secret:
  DB_HOST: Y29ybmVsaXVzLmRiLmVsZXBoYW50c3FsLmNvbQ==
  DB_PORT: NTQzMg==
  DB_USER: Z2VncXNsdm4=
  DB_PASSWORD: TGdTdlNWV0xpM212MEpsVEdJZTZtczBoM0hXZ0xIQ08=
  DB_NAME: Z2VncXNsdm4=
  JWT_SECRET: YWJjMTIz
  