apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-db-secret
type: Opaque
data:
    VITE_AUTH_API_URL: {{ .Values.secret.VITE_AUTH_API_URL }}
    VITE_PHOTOS_API_URL: {{ .Values.secret.VITE_PHOTOS_API_URL }}
