apiVersion: v1
kind: Service
metadata:
  name: {{ include "gallery-service.fullname" . }}
  labels:
    {{- include "gallery-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "gallery-service.selectorLabels" . | nindent 4 }}